export const REQUEST_CREATE_ADVERT =
  'REQUEST_CREATE_ADVERT';
export const CREATE_ADVERT = 'CREATE_ADVERT';
export const CREATE_ADVERT_FAILED = 'CREATE_ADVERT_FAILED';
export const REQUEST_GET_ADVERTS = 'REQUEST_GET_ADVERTS';
export const GET_ADVERTS = 'GET_ADVERTS';
export const GET_ADVERTS_FAILED = 'GET_ADVERTS_FAILED';
export const REQUEST_DELETE_ADVERTS =
  'REQUEST_DELETE_ADVERTS';
export const DELETE_ADVERTS = 'DELETE_ADVERTS';
export const DELETE_ADVERTS_FAILED =
  'DELETE_ADVERTS_FAILED';
