export const REQUEST_AUTH = 'REQUEST_AUTH';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILIED = 'AUTH_FAILED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const REQUEST_SIGNUP = 'REQUEST_SIGNUP';
