export const REQUEST_GET_CATEGORIES =
  'REQUEST_GET_CATEGORIES';
export const GET_CATEGORIES_SUCCESS =
  'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILED =
  'GET_CATEGORIES_FAILED';
export const REQUEST_ASSIGN_SKILL = 'REQUEST_ASSIGN_SKILL';
export const ASSIGN_SKILL_SUCCESS = 'ASSIGN_SKILL_SUCCESS';
export const ASSIGN_SKILL_FAILED = 'ASSIGN_SKILL_FAILED';

export const REQUEST_CREATE_CATEGORY =
  'REQUEST_CREATE_CATEGORY';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const CREATE_CATEGORY_FAILED =
  'CREATE_CATEGORY_FAILED';

export const REQUEST_UPDATE_CATEGORY =
  'REQUEST_UPDATE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const UPDATE_CATEGORY_FAILED =
  'UPDATE_CATEGORY_FAILED';

export const REQUEST_DELETE_CATEGORY =
  'REQUEST_DELETE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const DELETE_CATEGORY_FAILED =
  'DELETE_CATEGORY_FAILED';
