export const REQUEST_GET_CATEGORIES =
  'REQUEST_GET_CATEGORIES';
export const GET_CATEGORIES_SUCCESS =
  'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILED =
  'GET_CATEGORIES_FAILED';
export const REQUEST_ASSIGN_SKILL = 'REQUEST_ASSIGN_SKILL';
export const ASSIGN_SKILL_SUCCESS = 'ASSIGN_SKILL_SUCCESS';
export const ASSIGN_SKILL_FAILED = 'ASSIGN_SKILL_FAILED';
