export const REQUEST_GET_OFFERS = 'REQUEST_GET_OFFERS';
export const GET_ALL_OFFERS = 'GET_ALL_OFFERS';
export const GET_OFFERS_FAILED = 'GET_OFFERS_FAILED';
export const REQUEST_UPDATE_OFFER = 'REQUEST_UPDATE_OFFER';
export const UPDATE_OFFER = 'UPDATE_OFFER';
export const UPDATE_OFFER_FAILED = 'UPDATE_OFFER_FAILED';
