export const REQUEST_GET_SKILLS = 'REQUEST_GET_SKILLS';
export const GET_ALL_SKILLS = 'GET_ALL_SKILLS';
export const GET_SKILLS_FAILED = 'GET_SKILLS_FAILED';
export const REQUEST_ADD_SKILL_USER =
  'REQUEST_ADD_SKILL_USER';
export const ADD_SKILL_TO_USER = 'ADD_SKILL_TO_USER';
export const ADD_SKILL_TO_USER_FAILED =
  'ADD_SKILL_TO_USER_FAILED';

export const REQUEST_CREATE_SKILL = 'REQUEST_CREATE_SKIL';
export const CREATE_SKILL = 'CREATE_SKILL';
export const CREATE_SKILL_FAILED = 'CREATE_SKILL_FAILED';
