export const GET_SELF_PROFILE = 'GET_SELF_PROFILE';
export const REQUEST_GET_USERS = 'REQUEST_GET_USERS';
export const GET_USERS = 'GET_USERS';
export const GET_USERS_FAILED = 'GET_USERS_FAILED';
export const REQUEST_GET_ONE_USER = 'REQUEST_GET_ONE_USER';
export const GET_ONE_USER = 'GET_ONE_USER';
export const GET_ONE_USER_FAILED = 'GET_ONE_USER_FAILED';
